default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: volunteerly_development

test:
  <<: *default
  database: volunteerly_test

production:
  url: <%= ENV["DATABASE_URL"] %>